CREATE TABLE CLIENTE (
ID SERIAL PRIMARY KEY UNIQUE NOT NULL,
CPF BIGINT UNIQUE NOT NULL,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE CONTA (
ID SERIAL PRIMARY KEY UNIQUE NOT NULL,
USUARIO VARCHAR(50) UNIQUE NOT NULL,
SENHA VARCHAR(50) NOT NULL,
SALDO NUMERIC(10,2) NOT NULL,
CLIENTE BIGINT REFERENCES CLIENTE NOT NULL 
);

CREATE TABLE PRODUTO (
ID SERIAL PRIMARY KEY UNIQUE NOT NULL,
NOME VARCHAR(50) UNIQUE NOT NULL,
PRECO NUMERIC(10,2) NOT NULL
);

CREATE TABLE VENDA(
ID SERIAL PRIMARY KEY UNIQUE NOT NULL,
DATA_HORA TIMESTAMP NOT NULL,
CONTA INTEGER REFERENCES CONTA NOT NULL
);

CREATE TABLE PRODUTO_VENDA(
VENDA INTEGER REFERENCES VENDA NOT NULL,
PRODUTO INTEGER REFERENCES PRODUTO NOT NULL,
QTD INTEGER NOT NULL
);

CREATE TABLE MONETIZACAO(
CONTA INTEGER REFERENCES CONTA NOT NULL,
TIPO BOOLEAN NOT NULL,
VALOR NUMERIC(10,2) NOT NULL
);